const iconTypes = {
  account: "account",
  algorithms: "algorithms",
  arrowDown: "arrowDown",
  arrowLeft: "arrowLeft",
  arrowRight: "arrowRight",
  clear: "clear",
  close: "close",
  constructor: "constructor",
  delete: "delete",
  done: "done",
  draggable: "draggable",
  edit: "edit",
  help: "help",
  home: "home",
  info: "info",
  logout: "logout",
  manage: "manage",
  more: "more",
  play: "play",
  plus: "plus",
  result: "result",
  search: "search",
  settings: "settings",
  stats: "stats",
  tests: "tests",
  upload: "upload",
  uploadCloud: "uploadCloud",
};

export default iconTypes;
